server.port=5000

spring.datasource.url=jdbc:postgresql://172.24.10.182:5432/lyra_chatbot_dev
spring.datasource.username=tisal
spring.datasource.password=Tisal.2026
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

logging.level.org.springframework.boot.autoconfigure=ERROR

# Azure OpenAI configuration
azure.ai.openai.endpoint=https://joseus2.openai.azure.com/
azure.ai.openai.api-key=8MEX4bFJGkcEY5TQj67B532ObpTVHNiPZ1xq3ugSJLNCawtUKFGjJQQJ99CEACHYHv6XJ3w3AAABACOGAUQ2
azure.ai.openai.deployment-name=gpt-4.1-mini
azure.ai.openai.system-prompt=Eres un asistente util y profesional. Utiliza siempre un lenguaje claro.
azure.ai.openai.api-version=2023-05-15
azure.ai.openai.embedding-deployment=embeddings
